// Catégories d'ingrédients et leur ordre
export const INGREDIENT_CATEGORIES = {
  MEAT: 'meat',
  PRODUCE: 'produce',
  DAIRY: 'dairy',
  PANTRY_SAVORY: 'pantry-savory',
  PANTRY_SWEET: 'pantry-sweet',
  SPICE: 'spice',
  CONDIMENTS: 'condiments',
  BEVERAGES: 'beverages',
  OTHER: 'autres'
};

// Ordre des catégories pour le tri
export const CATEGORY_ORDER = [
  INGREDIENT_CATEGORIES.MEAT,
  INGREDIENT_CATEGORIES.PRODUCE,
  INGREDIENT_CATEGORIES.DAIRY,
  INGREDIENT_CATEGORIES.PANTRY_SAVORY,
  INGREDIENT_CATEGORIES.PANTRY_SWEET,
  INGREDIENT_CATEGORIES.SPICE,
  INGREDIENT_CATEGORIES.CONDIMENTS,
  INGREDIENT_CATEGORIES.BEVERAGES,
  INGREDIENT_CATEGORIES.OTHER
];

// Labels traduits pour les catégories
export const CATEGORY_LABELS = {
  [INGREDIENT_CATEGORIES.MEAT]: 'Viandes',
  [INGREDIENT_CATEGORIES.PRODUCE]: 'Fruits et Légumes',
  [INGREDIENT_CATEGORIES.DAIRY]: 'Produits Laitiers',
  [INGREDIENT_CATEGORIES.PANTRY_SAVORY]: 'Épicerie Salée',
  [INGREDIENT_CATEGORIES.PANTRY_SWEET]: 'Épicerie Sucrée',
  [INGREDIENT_CATEGORIES.SPICE]: 'Épices',
  [INGREDIENT_CATEGORIES.CONDIMENTS]: 'Condiments',
  [INGREDIENT_CATEGORIES.BEVERAGES]: 'Boissons',
  [INGREDIENT_CATEGORIES.OTHER]: 'Autres'
};
